language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php:
        - nightly

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - wget http://psvcg.coreteks.org/php-semver-checker-git.phar
  - php php-semver-checker-git.phar suggest -vvv

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
